# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Artifact
on:
  pull_request:
    types: [opened, reopened, ready_for_review, unlocked, synchronize]
jobs:
  build-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Initial Cleanup
      run: npm run clean
    - name: Install Angular
      run: npm install -g @angular/cli@18.0.3
    - name: Install dependencies
      run: npm install
    - name: Building Artifact
      run: npm run build
    - name: Final Cleanup
      run: npm run clean

  container-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build container images
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64
